# ~/.config/tmux/tmux.conf

# Better Prefix
# Đổi prefix từ Ctrl+b sang `
unbind C-b
set -g prefix `
bind ` send-prefix

# 1-based indexing
# Đánh số cửa sổ từ 1
set -g base-index 1
set -g pane-base-index 1

# Reload cấu hình
bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
 
# === Look & Feel ===

# True colors support
set -g default-terminal "${TERM}"
# set -g default-terminal "screen-256color" # Màu terminal 256 màu
set -sg terminal-overrides ",*:RGB"

# Status bar
set -g status-style bg=colour234,fg=colour136,bright
# set -g status-left "#[fg=green]#S "
# set -g status-right "#[fg=yellow,bright]%y-%m-%d %H:%M"

# Window buttons
set -g window-status-format "●"
set -g window-status-current-format "●"

set -g window-status-current-style "#{?window_zoomed_flag,fg=yellow,fg=magenta,nobold}"

set -g window-status-bell-style "fg=red,nobold"

# Options
set -g renumber-window on

# Pane separators
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style fg=magenta

# QoL
set -g escape-time 0
set -g mouse on # Hỗ trợ chuột
set -g repeat-time 1000
set -g history-limit 10000 # Tăng lịch sử cuộn

# keybindings: split
# Chia pane bằng | và - (hoặc h và v)
bind h split-window -hc "#{pane_current_path}"
bind | split-window -hc "#{pane_current_path}"
bind v split-window -vc "#{pane_current_path}"
bind - split-window -vc "#{pane_current_path}"

# keybindings: widows
bind c new-window -c "#{pane_current_path}"
bind -n C-Tab next-window
bind -n C-S-Tab previous-window

# keybindings: other
bind f resize-pane -Z
bind q detach-client
bind e choose-window -Z

# Chọn cửa sổ bằng alt + số cửa sổ
bind -n M-1 select-window -t :1
bind -n M-2 select-window -t :2
bind -n M-3 select-window -t :3
bind -n M-4 select-window -t :4
bind -n M-5 select-window -t :5
bind -n M-6 select-window -t :6
bind -n M-7 select-window -t :7
bind -n M-8 select-window -t :8
bind -n M-9 select-window -t :9

# keybindings: wasd
# Điều hướng pane bằng ` + wasd
bind w select-pane -U
bind a select-pane -L
bind s select-pane -D
bind d select-pane -R

# Thay đổi kích thước pane bằng ` + WASD
bind -r W resize-pane -U
bind -r A resize-pane -L
bind -r S resize-pane -D
bind -r D resize-pane -R

# keybindings: disable repeat for arows
# Điều hướng pane bằng ` + mũi tên
bind Up select-pane -U
bind Left select-pane -L
bind Down select-pane -D
bind Right select-pane -R


# Tpm plugins
set -g @plugin 'tmux-plugins/tpm'

# Catppuccin
set -g @plugin 'catppuccin/tmux'

# (Tùy chọn) Flavor
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_status_justify "absolute-centre"
set -g status-justify centre
set -g status-left "#{E:@catppuccin_status_session}"
set -g status-right "#[fg=#{@thm_fg}]%y-%m-%d %H:%M"
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"

# Khởi động TPM (phải ở cuối file)
run '~/.config/tmux/plugins/tpm/tpm'
